name: deploy
on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    if: github.repository == 'CoPoKo/ServiceAPIByVercel'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Deploy Private Key
        env:
          DEPLOY_KEY: ${{ secrets.TOKEN }}
          NAME: ${{ secrets.NAME }}
          EMAIL: ${{ secrets.EMAIL }}
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa 
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "$EMAIL"
          git config --global user.name "$NAME"
      - name: deploy
        run: |
          rm -rf .git
          git init
          git add .
          git commit -m "deploy"
          git branch -M main
          git remote add origin git@github.com:CoPoKoBot/service-api.git
          git push  --force --set-upstream origin main
